name: GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=GustavoN46&show_icons=true&include_all_commits=true&theme=omni&locale=en&hide_border=false
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=GustavoN46&layout=compact&langs_count=5&theme=omni&locale=en&hide_border=false
          path: profile/languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}
